version: '3.8'

services:
  climatezipcode:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV_VAR_NAME=env_var_value
    networks:
      - climate_network

networks:
  climate_network:
    driver: bridge